kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: test-default
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "list", "patch"]
  - apiGroups: ["batch"]
    resources: ["cronjobs"]
    verbs: ["create", "get", "list", "patch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: test-default
subjects:
  - kind: ServiceAccount
    name: default
    namespace: namespace
roleRef:
  kind: Role
  name: test-default
  apiGroup: rbac.authorization.k8s.io
